version: "3.9"

services:
  angular_app:
      container_name: angular_app
      image: devsu-angular_app:1.0.0
      build: ./angular/front-app/
      ports:
        - 4200:4200
      depends_on:
        - java_app
  java_app:
    container_name: java_app
    image: devsu-java_app:1.0.0
    build: .
    ports:
      - 8090:8090
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/devsu
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres